### PR TITLE
Dev sf ci

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Just a test. I think it will be useful to test against the dev version of sf so heads-up @agila5

**Comment by agila5** [comment]
Hi! Thank for your help. Just one question: this is just for testing or do you want to merge this PR at some point? 

btw: maybe it's easier to specify the dependency on the dev version of `sf` through [`usethis::use_dev_package()`](https://usethis.r-lib.org/reference/use_package.html)

**Comment by Robinlovelace** [comment]
It's generating some interesting error messages:

https://github.com/ITSLeeds/osmextract/pull/103/checks?check_run_id=931672088#step:11:21

**Comment by agila5** [comment]
I think the problem is somewhere between s2 and sf but I have no idea. `oe_match()` breaks when it's estimating which geofabrik areas are intersecting the input point (using EPSG: 4326), i.e. `provider[input_point, ]`.  At the moment I would just wait a couple of days more and leave the PR open as a remainder.

**Comment by agila5** [comment]
Hi @Robinlovelace, sorry to bother you. I just checked the R CMD check of osmextract on windows with github version of sf and it's running without any warning or error (just unrelated notes) so I want to test again with this PR. How can I add here all the commits in the master branch?

**Comment by Robinlovelace** [comment]
With the following commands in a system shell:

```
git checkout dev-sf-ci
git merge master
git push
```

**Comment by Robinlovelace** [comment]
Good timing: I was just about to open an issue here!

**Comment by agila5** [comment]
Hurray :tada: :tada: :tada:  Anyway, I wouldn't merge the PR since I think the double R CMD checks are unnecessarily "expensive". Maybe we can just leave it here and check the dev version of sf every now and then (like a few days before every major CRAN release). Or maybe we can merge it and change the .yaml file so that the extra checks are run onlyl if the text of the commit message include something like "test dev sf". What do you think?

**Comment by Robinlovelace** [comment]
> Maybe we can just leave it here and check the dev version of sf every now and then (like a few days before every major CRAN release)

:+1:

**Comment by agila5** [comment]
Just a random idea (that's probably an overkill for something as simple as the code here but it could be a useful test for other projects): maybe we could [schedule](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events) the dev sf ci workflow to run the first day of each month (or something similar). Thoughts?

**Comment by agila5** [comment]
Hi! I think that we can close this PR since that the package is on CRAN now and we should be notified of any problem with dev-sf when the maintainers run the revdep checks, right?

**Comment by Robinlovelace** [comment]
> Hi! I think that we can close this PR since that the package is on CRAN now and we should be notified of any problem with dev-sf when the maintainers run the revdep checks, right?

Not necessarily but I think we can close anyway. Great work getting it out there. Next up #92 + getting it out there!

**Pull request closed without merging**
